# Generated by Django 5.1.2 on 2024-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.TextField(),
        ),
    ]
